# Generated by Django 6.0.3 on 2026-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group11_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
