# Generated by Django 6.0.3 on 2026-04-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group11_app', '0002_remove_anomaly_description_remove_user_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='threatstatus',
            options={'verbose_name_plural': 'Threat Status'},
        ),
        migrations.RemoveField(
            model_name='recording',
            name='anomaly_flag_reason',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='is_anomaly',
        ),
    ]
