# Generated by Django 6.0.3 on 2026-04-15 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group11_app', '0003_alter_anomaly_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen Scientist'), ('researcher', 'Researcher')], default='citizen', max_length=20),
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to='recordings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
