# Generated by Django 6.0.3 on 2026-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group11_app', '0005_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
