# Generated by Django 6.0.3 on 2026-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group11_app', '0006_recording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
